### ISSUE TITLE
vjkl5问题

### ISSUE THREAD

**Issue by XingLong9630** [sixs/wenshu_spider#1]
在爬取的翻页过程中,经常出现remind key的问题.请问您有了解过吗

**Comment by sixs** [comment]
返回remind和remind key一种情况是出现了验证码反爬，还有一种情况是更新了js加密，你这情况是前者.

**Comment by XingLong9630** [comment]
非常感谢,明天尝试复现一下.谢谢您～

**Comment by sixs** [comment]
嗯嗯不用撒
