### ISSUE TITLE
验证码api

### ISSUE THREAD

**Issue by zamzus** [sixs/wenshu_spider#3]
你好，我有几个问题想请教一下：请问你当初研究这个网站时：
1）怎么知道出现remind key 或 remind 这两个东西的时候，是因为出现了验证码；
2）验证码的api< http://wenshu.court.gov.cn/User/ValidateCode>，和检查验证码的api<http://wenshu.court.gov.cn/Content/CheckVisitCode>您这边是怎么获取到的

**Comment by sixs** [comment]
1、最开始也不知道remind key和remind是什么意思，有一次出现返回结果为这个后，打开文书网站后发现出现验证码，多次尝试后发现情况均是如此，所以大胆猜测是出现验证码了.
2、验证码api和发送验证码请求api是出现验证码时，手动模拟输入验证码抓包得到的.

**Comment by zamzus** [comment]
嗯，谢谢
