### ISSUE TITLE
验证码已更新，checkcode模块失效

### ISSUE THREAD

**Issue by Thesharing** [sixs/wenshu_spider#9]
验证码已更新为带杂点的5位字母和数字

此外vl5x的计算函数也已经更新，请问应该怎么通过混淆的代码获取到原先的vl5x代码呢？

**Comment by marten-lee** [comment]
是的是的，急呢，拜请大神出面解决

**Comment by lixuliang** [comment]
请问楼上两位解决了吗？能分享一下吗。万分感谢！
